name: "Bug Report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this bug report!**
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g. When I try to upload a file, I get an unexpected error message.
    validations:
      required: true

