name: "Bug Report"
description: "File a bug report"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
