name: "Bug Report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this bug report!**
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g. When I try to upload a file, I get an unexpected error message.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior:
      placeholder: |
        1. Import client '....'
        2. Use API '....'
        3. Request data '...'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. The file should upload successfully and return a transaction ID.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or stack traces
      description: If applicable, add screenshots or stack traces to help explain your problem.
